#!/usr/bin/env bash
#Display information about subdomains.
information ()
{
    for arg
    do
	echo -n "The subdomain $arg is a "
	dig $arg."$domain" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print $4 " record and points to " $5}'
    done
}

domain="$1"
# sbdmain="$2"
if [ $# -eq 1 ]; then
    information www lb-01 web-01 web-02
else
    sbdmain="$2"
    information "$sbdmain"
fi
