#!/usr/bin/env bash
#Display information about subdomains.
function full_domain () {
    dig "www.$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print "The subdomain " substr($1,1,3) " is a " $4 " record and points to " $5 }'
    dig "lb-01.$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print "The subdomain " substr($1,1,5) " is a " $4 " record and points to " $5 }'
    dig "web-01.$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print "The subdomain " substr($1,1,6) " is a " $4 " record and points to " $5 }'
    dig "web-02.$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print "The subdomain " substr($1,1,6) " is a " $4 " record and points to " $5 }'
}

function sub_domain () {
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk -v a="$2" '{print "The subdomain " a " is a " $4 " record and points to " $5}'
}

if [ "$#" -eq 1 ]; then
    full_domain "$1"
elif [ "$#" -eq 2 ]; then
     sub_domain "$1" "$2"
fi
