#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me redirects to another page.
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=dQw4w9WgXcQ permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
