#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.5
apt-get -y update
apt-get -y install haproxy=1.5.\*
echo "backend web-backend
balance roundrobin
server 1454-web-01 34.75.211.47:80 check
server 1454-web-02 35.196.119.148:80 check
frontend http
bind *:80
mode http
default_backend web-backend
" >> /etc/haproxy/haproxy.cfg
