#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.5
sudo apt-get -y update
sudo apt-get -y install haproxy=1.5.\*
sudo sed -i "\$ a\listen 1454-lb-01\n\tbind *:80\n\tmode http\n\tstats enable\n\tbalance roundrobin\n\tserver 1454-web-01 34.75.211.47:80 check\n\tserver 1454-web-02 35.196.119.148:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
