#!/usr/bin/env bash
#Run Nginx as Nginx.
sudo pkill apache2
sudo chmod 777 /etc/nginx/nginx.conf
sudo chown nginx:nginx /etc/nginx/
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
